using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Windows.Forms;
using SgRevitAddin.Utils;

namespace SgRevitAddin.Commands.Modify.Games
{
    /// <summary>
    /// Pipe Mania — rotate-to-connect. A scrambled-but-always-solvable grid of pipe
    /// tiles runs from a riser (left) to a sprinkler (right). Click a tile to rotate
    /// it 90°; water fills the connected pipes live from the riser. Complete the run
    /// to the sprinkler before the pressure bar drains. Enter deals a new board.
    ///
    /// The puzzle is generated by carving a random simple path from source to sink,
    /// giving each path cell the straight/elbow piece that path demands, sprinkling
    /// decoy pieces elsewhere, then randomly rotating every tile — so a solution
    /// always exists (rotate the path tiles back), while the start is scrambled.
    /// </summary>
    public class PipeManiaDialog : DpiAwareForm
    {
        private const int Cols = 7, Rows = 5;
        private const int SrcRow = 2;                 // Rows / 2 — riser + sprinkler row
        private const float RoundSeconds = 45f;

        // Direction indices: 0=N, 1=E, 2=S, 3=W. Opening bits share the layout.
        private static readonly int[] DX  = { 0, 1, 0, -1 };
        private static readonly int[] DY  = { -1, 0, 1, 0 };
        private static readonly int[] BIT = { 1, 2, 4, 8 };
        private static readonly int[] OPP = { 4, 8, 1, 2 };   // bit facing back from the neighbour

        private const int InBit  = 8;   // source is fed from the West (riser)
        private const int OutBit = 2;   // sink drains to the East (sprinkler)

        private static readonly Color Blue    = Color.FromArgb(0x08, 0x59, 0x90);
        private static readonly Color Water   = Color.FromArgb(0x2A, 0x74, 0xAD);
        private static readonly Color Empty   = Color.FromArgb(0xB8, 0xC2, 0xCC);
        private static readonly Color BoardBg = Color.FromArgb(0xFB, 0xFD, 0xFE);
        private static readonly Color TileBg  = Color.FromArgb(0xF1, 0xF5, 0xF8);
        private static readonly Color TileEdge= Color.FromArgb(0xDD, 0xE4, 0xEA);
        private static readonly Color SinkRed = Color.FromArgb(0xC0, 0x28, 0x28);
        private static readonly Color Green   = Color.FromArgb(0x2E, 0x9E, 0x4F);
        private static readonly Color Amber   = Color.FromArgb(0xE0, 0x8A, 0x1C);
        private static readonly Color SubText = Color.FromArgb(0x33, 0x3A, 0x40);

        private enum State { Ready, Running, Won, Lost }

        private readonly GameCanvas _board;
        private readonly Label _score;
        private readonly Label _hint;
        private readonly Timer _timer;

        private readonly byte[,] _mask   = new byte[Cols, Rows];
        private readonly bool[,] _filled = new bool[Cols, Rows];
        private readonly Random _rng = new Random();

        private int _moves, _bestCs;      // best solve time in centiseconds (0 = none yet)
        private float _timeLeft;
        private bool _solved;
        private State _state = State.Ready;

        private readonly Font _overlayTitle = new Font("Segoe UI Semibold", 15f, FontStyle.Bold);
        private readonly Font _overlaySub   = new Font("Segoe UI", 9.5f);

        public PipeManiaDialog()
        {
            Text = "SG — Pipe Mania";
            AllowResize = false;
            RememberSize = false;

            const int M = 12, ScoreH = 22, HintH = 18, Tile = 60, Gap = 6, BarStrip = 12;
            int boardW = Cols * Tile + (Cols - 1) * Gap;
            int boardH = Rows * Tile + (Rows - 1) * Gap + BarStrip;

            _score = new Label
            {
                Location = new Point(M, 6),
                Size = new Size(boardW, ScoreH),
                Font = new Font("Segoe UI Semibold", 10.5f, FontStyle.Bold),
                ForeColor = Blue
            };
            Controls.Add(_score);

            _board = new GameCanvas
            {
                Location = new Point(M, 6 + ScoreH + 4),
                Size = new Size(boardW, boardH),
                BackColor = BoardBg
            };
            _board.Paint += Board_Paint;
            _board.MouseDown += Board_MouseDown;
            Controls.Add(_board);

            _hint = new Label
            {
                Location = new Point(M, _board.Bottom + 4),
                Size = new Size(boardW, HintH),
                Font = new Font("Segoe UI", 8.25f),
                ForeColor = SystemColors.GrayText,
                Text = "Click a tile to rotate it  •  connect the riser to the sprinkler  •  Space/Enter for a new board"
            };
            Controls.Add(_hint);

            ClientSize = new Size(M + boardW + M, _hint.Bottom + M);

            _bestCs = DialogMemory.GetInt(nameof(PipeManiaDialog), "BestCs", 0);

            _timer = new Timer { Interval = 100 };
            _timer.Tick += Tick;

            BuildPuzzle();
            _timeLeft = RoundSeconds;
            _state = State.Ready;
            UpdateScore();
        }

        // ── Puzzle generation ──
        private void BuildPuzzle()
        {
            List<Point> path = FindPath();
            var onPath = new bool[Cols, Rows];
            var sol = new byte[Cols, Rows];

            for (int i = 0; i < path.Count; i++)
            {
                Point cur = path[i];
                onPath[cur.X, cur.Y] = true;
                int m = 0;
                m |= (i == 0) ? InBit : DirBit(cur, path[i - 1]);
                m |= (i == path.Count - 1) ? OutBit : DirBit(cur, path[i + 1]);
                sol[cur.X, cur.Y] = (byte)m;
            }

            byte[] decoys = { 5, 3, 7 };   // straight, elbow, tee
            for (int x = 0; x < Cols; x++)
                for (int y = 0; y < Rows; y++)
                    if (!onPath[x, y]) sol[x, y] = decoys[_rng.Next(decoys.Length)];

            for (int x = 0; x < Cols; x++)
                for (int y = 0; y < Rows; y++)
                {
                    byte m = sol[x, y];
                    int r = _rng.Next(4);
                    for (int k = 0; k < r; k++) m = RotCW(m);
                    _mask[x, y] = m;
                }

            _moves = 0;
            RecomputeFill();
            // Don't hand the player an already-solved board.
            if (_solved) { _mask[0, SrcRow] = RotCW(_mask[0, SrcRow]); RecomputeFill(); }
            _board.Invalidate();
        }

        private List<Point> FindPath()
        {
            var visited = new bool[Cols, Rows];
            var path = new List<Point>();
            var start = new Point(0, SrcRow);
            var end = new Point(Cols - 1, SrcRow);
            visited[start.X, start.Y] = true;
            path.Add(start);
            if (Dfs(start, end, visited, path)) return path;

            path.Clear();   // fallback: straight shot across the middle row (always valid)
            for (int x = 0; x < Cols; x++) path.Add(new Point(x, SrcRow));
            return path;
        }

        private bool Dfs(Point cur, Point end, bool[,] visited, List<Point> path)
        {
            if (cur == end) return true;
            var dirs = new List<int> { 0, 1, 2, 3 };
            for (int i = dirs.Count - 1; i > 0; i--) { int j = _rng.Next(i + 1); int t = dirs[i]; dirs[i] = dirs[j]; dirs[j] = t; }
            foreach (int d in dirs)
            {
                int nx = cur.X + DX[d], ny = cur.Y + DY[d];
                if (nx < 0 || ny < 0 || nx >= Cols || ny >= Rows || visited[nx, ny]) continue;
                var np = new Point(nx, ny);
                visited[nx, ny] = true; path.Add(np);
                if (Dfs(np, end, visited, path)) return true;
                visited[nx, ny] = false; path.RemoveAt(path.Count - 1);
            }
            return false;
        }

        private static int DirBit(Point from, Point to)
        {
            int dx = to.X - from.X, dy = to.Y - from.Y;
            if (dx == 1) return 2;    // E
            if (dx == -1) return 8;   // W
            if (dy == 1) return 4;    // S
            return 1;                 // N
        }

        private static byte RotCW(byte m) => (byte)(((m << 1) | (m >> 3)) & 0xF);

        private void RecomputeFill()
        {
            Array.Clear(_filled, 0, _filled.Length);
            var start = new Point(0, SrcRow);
            _solved = false;
            if ((_mask[start.X, start.Y] & InBit) == 0) return;   // riser not connected in

            var q = new Queue<Point>();
            _filled[start.X, start.Y] = true;
            q.Enqueue(start);
            while (q.Count > 0)
            {
                Point c = q.Dequeue();
                byte m = _mask[c.X, c.Y];
                for (int d = 0; d < 4; d++)
                {
                    if ((m & BIT[d]) == 0) continue;
                    int nx = c.X + DX[d], ny = c.Y + DY[d];
                    if (nx < 0 || ny < 0 || nx >= Cols || ny >= Rows) continue;
                    if (_filled[nx, ny]) continue;
                    if ((_mask[nx, ny] & OPP[d]) == 0) continue;   // neighbour not open toward us
                    _filled[nx, ny] = true;
                    q.Enqueue(new Point(nx, ny));
                }
            }

            var sink = new Point(Cols - 1, SrcRow);
            _solved = _filled[sink.X, sink.Y] && (_mask[sink.X, sink.Y] & OutBit) != 0;
        }

        // ── Game flow ──
        private void NewGame()
        {
            BuildPuzzle();
            _timeLeft = RoundSeconds;
            _state = State.Running;
            _timer.Start();
            UpdateScore();
            _board.Invalidate();
        }

        private void OnEnter()
        {
            if (_state == State.Running) return;
            NewGame();
        }

        private void Tick(object sender, EventArgs e)
        {
            if (_state != State.Running) return;
            _timeLeft -= _timer.Interval / 1000f;
            if (_timeLeft <= 0f)
            {
                _timeLeft = 0f;
                _state = State.Lost;
                _timer.Stop();
            }
            UpdateScore();
            _board.Invalidate();
        }

        private void Board_MouseDown(object sender, MouseEventArgs e)
        {
            if (_state != State.Running) return;
            Layout(out int tile, out int gap, out int ox, out int oy, out int barH);
            for (int c = 0; c < Cols; c++)
                for (int r = 0; r < Rows; r++)
                {
                    var rect = new Rectangle(ox + c * (tile + gap), oy + r * (tile + gap), tile, tile);
                    if (!rect.Contains(e.Location)) continue;
                    _mask[c, r] = RotCW(_mask[c, r]);
                    _moves++;
                    RecomputeFill();
                    if (_solved)
                    {
                        _state = State.Won;
                        _timer.Stop();
                        int cs = (int)Math.Round((RoundSeconds - _timeLeft) * 100);
                        if (_bestCs == 0 || cs < _bestCs) _bestCs = cs;
                        DialogMemory.SetInt(nameof(PipeManiaDialog), "BestCs", _bestCs);
                        DialogMemory.Flush();
                    }
                    UpdateScore();
                    _board.Invalidate();
                    return;
                }
        }

        private void UpdateScore()
        {
            string best = _bestCs > 0 ? $"{_bestCs / 100f:0.0}s" : "—";
            _score.Text = $"Time: {(int)Math.Ceiling(_timeLeft)}s     Moves: {_moves}     Best: {best}";
        }

        protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
        {
            if (keyData == Keys.Enter || keyData == Keys.Space) { OnEnter(); return true; }
            return base.ProcessCmdKey(ref msg, keyData);
        }

        // ── Layout (derived from live panel size → DPI safe) ──
        private void Layout(out int tile, out int gap, out int ox, out int oy, out int barH)
        {
            int w = _board.ClientSize.Width, h = _board.ClientSize.Height;
            barH = Math.Max(6, h / 30);
            int usableH = h - barH - Math.Max(4, h / 40);
            gap = Math.Max(3, Math.Min(w, usableH) / 55);
            int tw = (w - (Cols - 1) * gap) / Cols;
            int th = (usableH - (Rows - 1) * gap) / Rows;
            tile = Math.Max(10, Math.Min(tw, th));
            int gridW = tile * Cols + gap * (Cols - 1);
            int gridH = tile * Rows + gap * (Rows - 1);
            ox = (w - gridW) / 2;
            oy = barH + Math.Max(4, h / 40) + (usableH - gridH) / 2;
        }

        // ── Rendering ──
        private void Board_Paint(object sender, PaintEventArgs e)
        {
            Graphics g = e.Graphics;
            g.SmoothingMode = SmoothingMode.AntiAlias;
            Layout(out int tile, out int gap, out int ox, out int oy, out int barH);
            int w = _board.ClientSize.Width, h = _board.ClientSize.Height;

            DrawPressureBar(g, w, barH);

            int radius = Math.Max(4, tile / 8);
            for (int c = 0; c < Cols; c++)
                for (int r = 0; r < Rows; r++)
                {
                    var rect = new Rectangle(ox + c * (tile + gap), oy + r * (tile + gap), tile, tile);
                    DrawTile(g, rect, radius, _mask[c, r], _filled[c, r]);
                }

            DrawEndpoints(g, tile, gap, ox, oy);

            if (_state != State.Running) DrawOverlay(g, w, h);
        }

        private void DrawPressureBar(Graphics g, int w, int barH)
        {
            int m = Math.Max(4, w / 40);
            var track = new Rectangle(m, (barH - Math.Max(4, barH / 2)) / 2 + 1, w - 2 * m, Math.Max(4, barH / 2));
            using (var b = new SolidBrush(Color.FromArgb(0xE3, 0xEA, 0xF0))) g.FillRectangle(b, track);
            float frac = Math.Max(0f, Math.Min(1f, _timeLeft / RoundSeconds));
            Color c = frac > 0.5f ? Green : frac > 0.25f ? Amber : SinkRed;
            var fill = new Rectangle(track.X, track.Y, (int)Math.Round(track.Width * frac), track.Height);
            using (var b = new SolidBrush(c)) g.FillRectangle(b, fill);
        }

        private void DrawTile(Graphics g, Rectangle rect, int radius, byte mask, bool filled)
        {
            using (var path = Round(rect, radius))
            {
                using (var b = new SolidBrush(TileBg)) g.FillPath(b, path);
                using (var p = new Pen(TileEdge)) g.DrawPath(p, path);
            }
            if (mask == 0) return;

            int cx = rect.X + rect.Width / 2, cy = rect.Y + rect.Height / 2;
            int t = Math.Max(6, rect.Width / 5);
            Color pipe = filled ? Water : Empty;

            using (var pen = new Pen(pipe, t) { StartCap = LineCap.Round, EndCap = LineCap.Round })
            {
                if ((mask & 1) != 0) g.DrawLine(pen, cx, cy, cx, rect.Y);            // N
                if ((mask & 2) != 0) g.DrawLine(pen, cx, cy, rect.Right, cy);        // E
                if ((mask & 4) != 0) g.DrawLine(pen, cx, cy, cx, rect.Bottom);       // S
                if ((mask & 8) != 0) g.DrawLine(pen, cx, cy, rect.X, cy);            // W
            }
            using (var b = new SolidBrush(pipe)) g.FillEllipse(b, cx - t / 2, cy - t / 2, t, t);
        }

        private void DrawEndpoints(Graphics g, int tile, int gap, int ox, int oy)
        {
            int t = Math.Max(6, tile / 5);
            // Riser inlet (left of the source cell).
            var src = new Rectangle(ox, oy + SrcRow * (tile + gap), tile, tile);
            int scy = src.Y + tile / 2;
            Color inColor = (_mask[0, SrcRow] & InBit) != 0 && _filled[0, SrcRow] ? Water : Empty;
            using (var pen = new Pen(inColor, t) { StartCap = LineCap.Round, EndCap = LineCap.Round })
                g.DrawLine(pen, src.X - gap - t, scy, src.X, scy);
            using (var b = new SolidBrush(Blue)) g.FillEllipse(b, src.X - gap - t - t / 2, scy - t, t * 3 / 2, t * 2);

            // Sprinkler outlet (right of the sink cell).
            var sink = new Rectangle(ox + (Cols - 1) * (tile + gap), oy + SrcRow * (tile + gap), tile, tile);
            int kcy = sink.Y + tile / 2;
            Color outColor = _solved ? Water : Empty;
            using (var pen = new Pen(outColor, t) { StartCap = LineCap.Round, EndCap = LineCap.Round })
                g.DrawLine(pen, sink.Right, kcy, sink.Right + gap + t, kcy);
            using (var b = new SolidBrush(SinkRed)) g.FillEllipse(b, sink.Right + gap + t - t / 2, kcy - t, t * 2, t * 2);
        }

        private void DrawOverlay(Graphics g, int w, int h)
        {
            string title, sub;
            Color titleColor;
            if (_state == State.Won)
            {
                title = "Flowing!";
                sub = $"Solved in {(RoundSeconds - _timeLeft):0.0}s, {_moves} move{(_moves == 1 ? "" : "s")}  •  Space/Enter for a new board";
                titleColor = Green;
            }
            else if (_state == State.Lost)
            {
                title = "Pressure lost";
                sub = "The riser ran dry  •  Space/Enter to try a new board";
                titleColor = SinkRed;
            }
            else
            {
                title = "Pipe Mania";
                sub = "Rotate tiles to connect the riser to the sprinkler  •  Space/Enter to start";
                titleColor = Blue;
            }

            using (var b = new SolidBrush(Color.FromArgb(205, Color.White)))
                g.FillRectangle(b, 0, h / 2 - 34, w, 68);
            TextRenderer.DrawText(g, title, _overlayTitle, new Rectangle(0, h / 2 - 30, w, 28),
                titleColor, TextFormatFlags.HorizontalCenter);
            TextRenderer.DrawText(g, sub, _overlaySub, new Rectangle(0, h / 2 + 2, w, 20), SubText,
                TextFormatFlags.HorizontalCenter);
        }

        private static GraphicsPath Round(Rectangle r, int radius)
        {
            var path = new GraphicsPath();
            int d = Math.Min(radius * 2, Math.Min(r.Width, r.Height));
            if (d <= 1) { path.AddRectangle(r); return path; }
            path.AddArc(r.X, r.Y, d, d, 180, 90);
            path.AddArc(r.Right - d, r.Y, d, d, 270, 90);
            path.AddArc(r.Right - d, r.Bottom - d, d, d, 0, 90);
            path.AddArc(r.X, r.Bottom - d, d, d, 90, 90);
            path.CloseFigure();
            return path;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _timer?.Dispose();
                _overlayTitle?.Dispose();
                _overlaySub?.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
